[package]
name = "cli-dungeon-rules"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
derive_more = { version = "2", features = ["full"]}

